create table if not exists public.site_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 120),
  email text check (
    email is null
    or email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
  ),
  project_type text not null default 'Company site',
  message text not null check (char_length(message) between 8 and 2000),
  source text not null default 'nxwarden.com'
);

alter table public.site_submissions enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on public.site_submissions to anon, authenticated;
grant usage, select on sequence public.site_submissions_id_seq to anon, authenticated;

drop policy if exists "Anyone can submit NX Warden forms" on public.site_submissions;

create policy "Anyone can submit NX Warden forms"
on public.site_submissions
for insert
to anon, authenticated
with check (true);
